eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: provider-log
  data:
    mongodb:
      port: 27017
      database: test

